# Generated by Django 5.1.5 on 2026-08-07 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LPRScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente_leida', models.CharField(max_length=10)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_foto', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID del usuario que paga')),
                ('patente', models.CharField(help_text='Patente estacionada', max_length=10)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=15)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID del usuario en Casilda Conecta')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito (Carga)'), ('DEBITO', 'Débito (Pago Estacionamiento)')], max_length=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID del usuario en Casilda Conecta')),
                ('patente', models.CharField(max_length=10)),
                ('alias', models.CharField(blank=True, help_text='Ej: Mi Auto', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('user_id', models.IntegerField(help_text='ID del usuario en Casilda Conecta', primary_key=True, serialize=False)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.lprscan')),
            ],
        ),
        migrations.AddField(
            model_name='lprscan',
            name='parking_session',
            field=models.ForeignKey(blank=True, help_text='Nulo si no tenía pago activo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parkingsession'),
        ),
    ]
