# Generated by Django 5.2.17 on 2026-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicle_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('user_id', models.IntegerField(help_text='ID del usuario en Casilda Conecta', primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('VECINO', 'Vecino'), ('INSPECTOR', 'Inspector'), ('EMPLEADO', 'Empleado Municipal')], default='VECINO', max_length=20)),
            ],
        ),
    ]
